server:
  port: 8081
  servlet:
    context-path: /user
spring:
  datasource:
    url: jdbc:mysql://111.231.221.220:4406/db_make_well_mysql
    username: root
    password: 123456
#注册时的名字
  application:
    name: user-service
#服务注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka