server:
  port: 8081
  servlet:
    context-path: /user
spring:
  datasource:
    url: jdbc:mysql://111.231.221.220:4406/db_make_well_mysql
    username: root
    password: 123456
  mvc:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: cn.ticast.book.pojo